#! /bin/python

bash ~/aou_sc_predixcan/00wrapper.sh --pop META --phecode CV_404 --ref CD14-low_CD16-positive_monocyte --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref CD14-positive_monocyte --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref CD16-negative_CD56-bright_natural_killer_cell_human --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref CD4-positive_alpha-beta_cytotoxic_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref CD4-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref CD8-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref central_memory_CD4-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref central_memory_CD8-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref conventional_dendritic_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref dendritic_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref double_negative_thymocyte --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref effector_memory_CD4-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref effector_memory_CD8-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref erythrocyte --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref gamma-delta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref hematopoietic_precursor_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref innate_lymphoid_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref memory_B_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref mucosal_invariant_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref naive_thymus-derived_CD4-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref naive_thymus-derived_CD8-positive_alpha-beta_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref natural_killer_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref peripheral_blood_mononuclear_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref plasmablast --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref plasmacytoid_dendritic_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref platelet --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref regulatory_T_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref transitional_stage_B_cell --cell_type immune
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Acinar --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Activated_stellate --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Alpha --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Beta --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Delta --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Ductal --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Endothelial --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Epsilon --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Gamma --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Immune --cell_type islet
python ~/aou_sc_predixcan/03run_predixcan.py --pop META --phecode CV_404 --ref Quiescent_stellate --cell_type islet
